apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: mobile
{{- include "labels" . }}
spec:
  revisionHistoryLimit: 10
  replicas: 1
  strategy:
      type: RollingUpdate
      rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
  selector:
    matchLabels:
      app_name: {{ .Chart.Name }}
  template:
    metadata:
    {{- include "labels" . | indent 4 }}
    spec:
      containers:
      - name: pipeline-spawner
        image: {{ .Values.kubernetes.repo.host }}:{{ .Values.kubernetes.repo.port }}/ukiss/pipeline-spawner:{{ .Chart.Version }}
        resources:
          limits:
            memory: {{ .Values.kubernetes.limits.memory }}
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        ports:
        - containerPort: {{ .Values.properties.app.port }}
        livenessProbe:
          httpGet:
            path: /static/content/index.html
            port: {{ .Values.properties.app.port }}
          initialDelaySeconds: 180
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /static/content/index.html
            port: {{ .Values.properties.app.port }}
          initialDelaySeconds: 10
          failureThreshold: 1
          timeoutSeconds: 15
      securityContext:
        runAsNonRoot: true
        runAsUser: 4659
        fsGroup: 4659
      restartPolicy: Always